port: "80"
limitMaxConnections: 20

db:
  host: "localhost" # endpoint - по АПИ будем ходить на localhost
  port: "5432"
  schema: ""
  dbname: "postgres"
  sslmode: "disable"
  salt: "s11212-df2309dsfso1[9wasdf1[0wf23"
  signingKey: "jkad2s3_)()f*^(&le23#a0d9"